spring:
    datasource:
        url: jdbc:mysql://localhost:3306/member
        username: root
        password: "#moon2005" # ??? mysql ?? ?? ? ??? ?? ??

jpa:
    hibernate:
        ddl-auto: update # ???? ?? ?? ??? ???? ??? ??? ??
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect # ??? ?????? SQL ?? ??
    show-sql: true # ???? SQL? ??? ???? ??
